blitz , gs-sftp

diff --git a/tools/blitz b/tools/blitz
--- a/tools/blitz
+++ b/tools/blitz
@@ -25,6 +25,9 @@ RSYNC_CLIENT_DEFAULTS="-ahPRv"
 BIN=$(echo "${0}" | sed 's/blitz$/'"${GS_NETCAT_BIN}"'/')
 [[ x"${BIN}" != x"${0}" ]] && [[ -f "${BIN}" ]] && GS_NETCAT_BIN="${BIN}"
 
+command -v "${GS_NETCAT_BIN}" >/dev/null 2>&1 || { echo >&2 "${GS_NETCAT_BIN} not found. Check PATH=?"; exit 1; }
+command -v rsync >/dev/null 2>&1 || { echo >&2 "rsync not found. Try 'apt-get install rsync' or check PATH=?"; exit 1; }
+
 usage()
 {
 	printf "\
@@ -100,6 +103,14 @@ while getopts ":hgs:k:o:L:" opt; do
 	esac
 done
 
+if [[ "$*" == *"-l"* ]]; then
+	IS_SERVER=1
+else
+	shift $((OPTIND -1))	# list of files...
+	# echo "Remaining (files): $*"
+	[[ -z $* ]] && { echo >&2 "ERROR: No files specified."; usage; }
+fi
+
 # Prepare existing GSOCKET_ARGS to take more arguments if there are any
 [[ -n "$GSOCKET_ARGS" ]] && GSOCKET_ARGS+=" "
 # Already got password in env-variable -> DONT ASK again.
@@ -119,17 +130,12 @@ ENV_ARGS="${GSOCKET_ARGS}${GSNC_ENV_ARGS[*]}"
 # echo gsnc-env-args : \'${GSNC_ENV_ARGS[@]}\'
 # echo rsync-args    : ${RSYNC_ARGS}
 
-command -v "${GS_NETCAT_BIN}" >/dev/null 2>&1 || { echo >&2 "${GS_NETCAT_BIN} not found. Check PATH=?"; exit 1; }
-command -v rsync >/dev/null 2>&1 || { echo >&2 "rsync not found. Try 'apt-get install rsync' or check PATH=?"; exit 1; }
-
-if [[ "$*" == *"-l"* ]]; then
+if [[ -n ${IS_SERVER} ]]; then
 	# SERVER
 	ENV_ARGS="${GSOCKET_ARGS}${GSNC_ENV_ARGS[*]}"
 	GSOCKET_ARGS="${ENV_ARGS}" exec "${GS_NETCAT_BIN}" "${ARGS_NEW[@]}" -e "rsync ${RSYNC_SERVER_DEFAULTS} ${RSYNC_ARGS} ."
 else
 	# CLIENT
-	shift $((OPTIND -1))	# list of files...
-	# echo "Remaining: $*"
 	ARGS=" -q"
 	# ARGS=""
 	[[ -n ${ARGS_NEW[*]} ]] && ARGS+=" ${ARGS_NEW[*]}"
diff --git a/tools/gs-sftp b/tools/gs-sftp
--- a/tools/gs-sftp
+++ b/tools/gs-sftp
@@ -19,6 +19,8 @@ GSNC_PARAMS=""
 # GSNC_PARAMS+="-q "	# quite mode
 GSNC_PARAMS+="-w "	# Client to wait until server becomes available
 
+
+
 usage()
 {
 	printf "\
@@ -61,6 +63,12 @@ read_password()
 	fi
 	echo "${password}" | tr -d "[:space:]"
 }
+
+command -v "${GS_NETCAT_BIN}" >/dev/null 2>&1 || { echo >&2 "${GS_NETCAT_BIN} not found. Check PATH=?"; exit 1; }
+command -v sftp >/dev/null 2>&1 || { echo >&2 "sftp not found. Try 'apt-get install openssh' or check PATH=?"; exit 1; }
+
+SFTP_SERVER_BIN=$(find_binary sftp-server "$PREFIX"/lib /usr/lib/ /usr/local/lib /usr/libexec)
+[[ -z "${SFTP_SERVER_BIN}" ]] && { echo >&2 "sftp-server binary not found."; exit 1; }
 
 OPTERR=0
 FL_NEED_PASSWORD=1
@@ -111,11 +119,6 @@ if [[ -n "$FL_NEED_PASSWORD" ]]; then
 fi
 ENV_ARGS="${GSOCKET_ARGS}${GSNC_ENV_ARGS[*]}"
 
-command -v "${GS_NETCAT_BIN}" >/dev/null 2>&1 || { echo >&2 "${GS_NETCAT_BIN} not found. Check PATH=?"; exit 1; }
-command -v sftp >/dev/null 2>&1 || { echo >&2 "sftp not found. Try 'apt-get install openssh' or check PATH=?"; exit 1; }
-
-SFTP_SERVER_BIN=$(find_binary sftp-server "$PREFIX"/lib /usr/lib/ /usr/local/lib /usr/libexec)
-[[ -z "${SFTP_SERVER_BIN}" ]] && { echo >&2 "sftp-server binary not found."; exit 1; }
 
 if [[ "$*" == *"-l"* ]]; then
 	# SERVER
@@ -123,7 +126,7 @@ if [[ "$*" == *"-l"* ]]; then
 	GSOCKET_ARGS="${ENV_ARGS}" exec "${GS_NETCAT_BIN}" "${ARGS_NEW[@]}" -e "${SFTP_SERVER_BIN}"
 else
 	# CLIENT
-	ARGS=""
+	ARGS=" -q"
 	[[ -n ${ARGS_NEW[*]} ]] && ARGS=" ${ARGS_NEW[*]}"
 	# shellcheck disable=SC2086 # Double quote to prevent globbing and word splitting. ${RSYNC_ARGS} -> We want word splitting for multiple arugments.
 	GSOCKET_ARGS="${ENV_ARGS}${ARGS}" exec sftp -D "${GS_NETCAT_BIN}"
