test cases

diff --git a/tools/gs b/tools/gs
--- a/tools/gs
+++ b/tools/gs
@@ -14,6 +14,7 @@ ${BIN_NAME} [-k file] [-s password] <programm> <parameters>
    -s <secret>  Secret (e.g. password).
    -k <file>    Read Secret from file.
    -p <ports>   Range of listening ports to redirect [default=all]
+   -T           Use TOR.
 
 Example:
     $ ${1} -s MySecret /usr/bin/sshd -d         # Server
@@ -26,6 +27,7 @@ See 'gs-netcat -h' for more options."
 my_getopt()
 {
 	OPTERR=0
+	# shellcheck disable=SC2034 # FL_NEED_PASSWORD appears unused. => used i env_arg_init
 	FL_NEED_PASSWORD=1
 	# Check if -s or -k is already supplied in environment and dont ask again.
 	[[ "$GSOCKET_ARGS" =~ ^'-s' ]] && unset FL_NEED_PASSWORD
@@ -33,7 +35,7 @@ my_getopt()
 	[[ "$GSOCKET_ARGS" =~ ^'-k' ]] && unset FL_NEED_PASSWORD
 	[[ "$GSOCKET_ARGS" =~ ' -k' ]] && unset FL_NEED_PASSWORD
 	# shellcheck disable=SC2220 # Invalid flags are not handled. Add a *) case.
-	while getopts ":qhgp:s:k:L:" opt; do
+	while getopts ":qhgTp:s:k:L:" opt; do
 		case ${opt} in
 			s )
 				# GSNC_ENV_ARGS[${#GSNC_ENV_ARGS[@]}]="-s"	# Add to end of array
@@ -45,7 +47,7 @@ my_getopt()
 				# GSNC_ENV_ARGS[${#GSNC_ENV_ARGS[@]}]="-k"	# Add to end of array
 				KFILE=$(cd "$(dirname "$OPTARG")" && pwd)/$(basename "$OPTARG")
 				[[ -f "${KFILE}" ]] || { echo >&2 "File not found: ${KFILE}"; exit 255; }
-				GSOCKET_SECRET=$(<${KFILE})
+				GSOCKET_SECRET=$(<"${KFILE}")
 				# GSNC_ENV_ARGS[${#GSNC_ENV_ARGS[@]}]="${KFILE}"	# Add to end of array
 				# KFILE=$(eval echo "$OPTARG")	# Add to end of array
 				# GSNC_ENV_ARGS[${#GSNC_ENV_ARGS[@]}]=$(eval echo "$OPTARG")	# Add to end of array
@@ -61,7 +63,12 @@ my_getopt()
 			p )
 				GS_HIJACK_PORTS="${OPTARG}"
 				;;
+			T )
+				[[ -z "${GSOCKET_SOCKS_IP}" ]] && GSOCKET_SOCKS_IP="127.0.0.1"
+				;;
+
 			q )
+				# shellcheck disable=SC2034 # IS_QUIET appears unused. => Used in env_arg_init
 				IS_QUIET=1
 				ARGS_NEW[${#ARGS_NEW[@]}]="-q"
 				;;
@@ -80,31 +87,36 @@ my_getopt()
 	[[ -n "${GSOCKET_SECRET}" ]] && unset FL_NEED_PASSWORD
 }
 
+# default values
+GS_HIJACK_PORTS="1-65535"
 gs_init
-my_getopt $@
+my_getopt "$@"
 shift $((OPTIND -1))
-env_arg_init
 
 if [[ x"$OSTYPE" == "xdarwin"* ]]; then
 	# OSX does not allow LD_PRELOAD of binaries in /usr/. Copy to tmp...
 	ROOTDIR=$(mktemp -d -t thc-gs)
-	PBIN_FULLPATH=$(which $1)
-	[[ $? -ne 0 ]] && { $1; exit 1; }
+	PROGBIN_FULLPATH=$(which "$1")
+
+	[[ -z "$PROGBIN_FULLPATH" ]] && { echo >&2 "${1}: command not found"; exit 1; }
 	# FIXME: temp file is only cleaned on reboot. Hmm...
-	cp "${PBIN_FULLPATH}" "${ROOTDIR}/" &>/dev/null
-	PBIN_NAME="$(basename "${1}")" # programm binary
-	PBIN="${ROOTDIR}/${PBIN_NAME}"
+	cp "${PROGBIN_FULLPATH}" "${ROOTDIR}/" &>/dev/null
+	PROGBIN_NAME="$(basename "${1}")" # programm binary
+	PROGBIN="${ROOTDIR}/${PROGBIN_NAME}"
 else
 	ROOTDIR=""
-	PBIN="${1}"
+	PROGBIN="${1}"
 fi
+
+env_arg_init
 shift 1
 
 # echo  GS_NETCAT_BIN=${GS_NETCAT_BIN} GSOCKET_ARGS="${ENV_ARGS} ${ARGS_NEW[*]}" GSOCKET_SECRET="${GSOCKET_SECRET}" DYLD_INSERT_LIBRARIES=${GS_SO_BIN} DYLD_FORCE_FLAT_NAMESPACE=1 exec "${PBIN}" $@
 
 if [[ x"$OSTYPE" == "xdarwin"* ]]; then
-	GS_NETCAT_BIN=${GS_NETCAT_BIN} GS_HIJACK_PORTS="${GS_HIJACK_PORTS}" GSOCKET_ARGS="${ENV_ARGS} ${ARGS_NEW[*]}" GSOCKET_SECRET="${GSOCKET_SECRET}" DYLD_INSERT_LIBRARIES=${GS_SO_BIN} DYLD_FORCE_FLAT_NAMESPACE=1 exec "${PBIN}" $@
+	echo GS_NETCAT_BIN=${GS_NETCAT_BIN} GS_HIJACK_PORTS="${GS_HIJACK_PORTS}" GSOCKET_SOCKS_IP="${GSOCKET_SOCKS_IP}" GSOCKET_ARGS="${ENV_ARGS} ${ARGS_NEW[*]}" GSOCKET_SECRET="${GSOCKET_SECRET}" DYLD_INSERT_LIBRARIES=${GS_SO_BIN} DYLD_FORCE_FLAT_NAMESPACE=1 exec "${PROGBIN}" "$@"
+	GS_NETCAT_BIN=${GS_NETCAT_BIN} GS_HIJACK_PORTS="${GS_HIJACK_PORTS}" GSOCKET_SOCKS_IP="${GSOCKET_SOCKS_IP}" GSOCKET_ARGS="${ENV_ARGS} ${ARGS_NEW[*]}" GSOCKET_SECRET="${GSOCKET_SECRET}" DYLD_INSERT_LIBRARIES=${GS_SO_BIN} DYLD_FORCE_FLAT_NAMESPACE=1 exec "${PROGBIN}" "$@"
 else
-	GS_NETCAT_BIN=${GS_NETCAT_BIN} GS_HIJACK_PORTS="${GS_HIJACK_PORTS}" GSOCKET_ARGS="${ENV_ARGS} ${ARGS_NEW[*]}" GSOCKET_SECRET="${GSOCKET_SECRET}" LD_PRELOAD=${GS_SO_BIN} exec "${PBIN}" $@
+	GS_NETCAT_BIN=${GS_NETCAT_BIN} GS_HIJACK_PORTS="${GS_HIJACK_PORTS}" GSOCKET_SOCKS_IP="${GSOCKET_SOCKS_IP}" GSOCKET_ARGS="${ENV_ARGS} ${ARGS_NEW[*]}" GSOCKET_SECRET="${GSOCKET_SECRET}" LD_PRELOAD=${GS_SO_BIN} exec "${PROGBIN}" "$@"
 fi
 
