dynamic shared object go into $PREFIX/lib now.

diff --git a/tools/gs_funcs b/tools/gs_funcs
--- a/tools/gs_funcs
+++ b/tools/gs_funcs
@@ -1,5 +1,8 @@
 #! /usr/bin/env bash
 
+
+[[ $(basename "$0") = "gs_funcs" ]] && { echo "Use gsocket, gs-netcat, gs-sftp, gs-mount or blitz instead."; exit 1; }
+
 # Find a sftp-server binary
 find_binary()
 {
@@ -161,6 +164,29 @@ ls ./../denied/exist-denied.txt"
 	rm -rf "${ROOTDIR}/sftp-server.sh" &>/dev/null
 }
 
+
+gs_find_so_single()
+{
+	[[ -e "${1}/${2}" ]] && { echo "$(cd "${1}" || exit; pwd)""/${2}"; }
+}
+
+# Search for the dynamic shared object file.
+# 1. Try $basedir
+# 2. Try ${basedir}/../lib
+# 3. Try /usr/lib
+# 4. Try /usr/local/lib
+# Return absolute path to DSO. 
+gs_find_so()
+{
+	for dir in "${BASEDIR}" "${1}/lib" "/usr/lib" "/usr/local/lib"; do
+		res=$(gs_find_so_single "${dir}" "${2}")
+		[[ -z "$res" ]] || { echo "$res"; return; }
+	done
+
+	echo >&2 "gsocket: ${1} not found."
+	exit 5
+}
+
 gs_init()
 {
 	GS_NETCAT_BIN="gs-netcat"
@@ -173,14 +199,16 @@ gs_init()
 		EXE=".exe"
 	fi
 
-	UCHROOT_BIN="${BASEDIR}/gs_uchroot_so${EXE}"
-	[[ -f "${UCHROOT_BIN}" ]] || { echo >&2 "${UCHROOT_BIN} not found."; exit 2; }
-
-	GS_SO_BIN="${BASEDIR}/gs_so${EXE}"
-	[[ -f "${GS_SO_BIN}" ]] || { echo >&2 "${GS_SO_BIN} not found."; exit 2; }
-
-	# To find sftp-server in PREFIX/lib
+	# To find sftp-server and DSO's in PREFIX/lib
 	PREFIX="$(cd "$(dirname "${0}")/../" || exit; pwd)"
+
+	# on OSX the dl-files are called .bundle (not .dylib) but it is generally
+	# accepted to call them .so. OSX keep those is /System/Library/gsocket
+	# but automake insists on ${PREFIX}/lib
+	UCHROOT_BIN=$(gs_find_so "$PREFIX" "gs_uchroot.so${EXE}")
+	# shellcheck disable=SC2034 # appears unused. Verify use (or export if used externally).
+	GS_SO_BIN=$(gs_find_so "$PREFIX" "gs.so${EXE}")
+
 	# shellcheck disable=SC2034 # appears unused. Verify use (or export if used externally).
 	BIN_NAME="$(basename "${0}")"
 
@@ -306,7 +334,7 @@ sftp_server_start()
 		if [[ -n "${IS_UCHROOT}" ]]; then
 			ROOTDIR=$(mktemp -d -t thc-gs-sftp-XXXXXXXXXXXXXXX) 
 		fi
-		SFTP_SERVER_BIN=$(find_binary sftp-server${EXE} "$PREFIX"/lib /opt/csw/libexec /usr/lib /usr/local/lib /usr/libexec /usr/libexec/openssh /usr/lib/ssh /usr/sbin)
+		SFTP_SERVER_BIN=$(find_binary sftp-server${EXE} "${PREFIX}/lib" /opt/csw/libexec /usr/lib /usr/local/lib /usr/libexec /usr/libexec/openssh /usr/lib/ssh /usr/sbin)
 		PRELOAD="LD_PRELOAD=${UCHROOT_BIN}"
 	fi
 	[[ -z "${SFTP_SERVER_BIN}" ]] && { echo >&2 "sftp-server binary not found."; exit 1; }
